export { default as bmp } from './parsers_sync/bmp';
export { default as gif } from './parsers_sync/gif';
export { default as ico } from './parsers_sync/ico';
export { default as jpeg } from './parsers_sync/jpeg';
export { default as png } from './parsers_sync/png';
export { default as psd } from './parsers_sync/psd';
export { default as svg } from './parsers_sync/svg';
export { default as tiff } from './parsers_sync/tiff';
export { default as webp } from './parsers_sync/webp';
