export { default as bmp } from './parsers/bmp';
export { default as gif } from './parsers/gif';
export { default as ico } from './parsers/ico';
export { default as jpeg } from './parsers/jpeg';
export { default as png } from './parsers/png';
export { default as psd } from './parsers/psd';
export { default as svg } from './parsers/svg';
export { default as tiff } from './parsers/tiff';
export { default as webp } from './parsers/webp';
